#!/usr/bin/env bash

DATABASE_PORT=$(if [ -z "${CI+x}" ]; then echo 5473; else echo 5474; fi)
DATABASE_HOST=$(if [ -z "${CI+x}" ]; then echo localhost; else echo 172.17.0.1; fi)

export NODE_ENV="test"
export DATABASE_URL="postgres://admin:password@${DATABASE_HOST}:${DATABASE_PORT}/dumpster-fire-test"

yarn run --silent db:start --drop
