#!/bin/bash

IMAGE="dumpster-fire-ci"
TAG=${1:-latest}

docker build \
  --force-rm \
  --tag="${IMAGE}:${TAG}" \
  container/ci && \

docker run \
  --rm \
  --workdir /app/user \
  -v "$(pwd)":/app/user \
  -v /var/run/docker.sock:/var/run/docker.sock \
  "${IMAGE}":"${TAG}" \
  /verify.sh
