#!/bin/bash

SCRIPT_DIR=$(dirname "$0")

ENVIRONMENT=production \
GITHUB_TOKEN=${GITHUB_TOKEN?:is required} \
HEROKU_TOKEN=${HEROKU_TOKEN?:is required} \
RELEASE_TAG=${RELEASE_TAG:-latest} \
SLACK_URL=${SLACK_URL?:is required} \
$SCRIPT_DIR/index
